name: "Spoolman Server"
version: edge
description: "Run the latest stable version of Spoolman."
url: "https://github.com/donkie/spoolman"
slug: "spoolman_server"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: application
udev: true
webui: "[PROTO:option_name]://[HOST]:[PORT:8000]"
environment:
  SPOOLMAN_DIR_DATA: "/addons/spoolman"
map:
  - config:rw  
  - addons:rw
boot: auto
ports:
  8000/tcp: 8000
