name: "Spoolman Server (dev)"
version: edge
description: "Run the latest stable version of Spoolman."
url: "https://github.com/donkie/spoolman"
slug: "spoolman_server_dev"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: application
udev: true
homeassistant_api: false
auth_api: false
host_network: false
ingress: true
ingress_port: 8000
webui: "[PROTO:option_name]://[HOST]:[PORT:8000]"
panel_icon: mdi:printer-3d
panel_title: Spoolman
panel_admin: false
stage: experimental
environment:
  SPOOLMAN_DIR_DATA: "/addons/spoolman"
  SPOOLMAN_BASE_PATH: "homeassistant:8000"
map:
  - config:rw  
  - addons:rw
boot: auto
ports:
  8000/tcp: 8000
